### ISSUE TITLE
Blade Sintax Error Unexpected: End of File Expected: T_BLADE_COMMENT, T_BLADE_STOP

### ISSUE THREAD

**Issue by angeljqv** [haidubogdan/netbeans-php-blade-plugin#14]
From #12, I have that problem too, i don't know how to avoid it

> ```blade
> <script>
> // @ (
> </script>
> ```
> ```blade
> <script>
> // @ ''(
> </script>
> ```
> ```blade
> @section('content')
>   <td style="mso-number-format:&#39;@&#39;;"></td>
> @endsection
> ```
> ```blade
> @section('content')
>   <span data-formatcode="@"></td>
> @endsection
> ```
> 
> **Blade Sintax Error** **Unexpected:** End of File **Expected:** T_BLADE_COMMENT, T_BLADE_STOP
> 
> when after `@` there is a especial character or a space it is not a blade directive

**Comment by haidubogdan** [comment]
Hi I've did some updates. I hope this issue is fixed.
https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/v.1.0.0.6-beta

This parse error is due to LESS parser, I think it's not directly related with the plugin.
@section('content')
  <td style="mso-number-format:&#39;@&#39;;"></td>
@endsection

**Comment by angeljqv** [comment]
>This parse error for the snippet bellow is due to LESS parser
> ```blade
> @section('content')
>   <td style="mso-number-format:&#39;@&#39;;"></td>
> @endsection
> ```

If you disable `LESS parser`,  **Blade Sintax Error** pop up, but it doesn't matter to me, thanks
