### ISSUE TITLE
[BUG] Netbeans freezes and stop working when i'm trying to write a class static inside a directive

### ISSUE THREAD

**Issue by parallels999** [haidubogdan/netbeans-php-blade-plugin#25]
Try to write letter by letter on blade file
```blade
@test([ Test1::class, Test2::class, Test3::class ])
```

**Comment by haidubogdan** [comment]
I know about it ... it seems to be a bit tricky and the fix might take a while.

**Comment by haidubogdan** [comment]
Hi I've pushed a patch on the release https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb-14102022
The php lexer embedding seems to crash on operations when a embedded text contains "label:text".
The "patchy" solution is to detect in the embeded php text this kind of syntax and see it as plain HTML

**Comment by parallels999** [comment]
Thanks, it don`t freezes  anymore

**Comment by parallels999** [comment]
@haidubogdan hi, it freezes again on current version, is a regression??

> Try to write letter by letter on blade file
>
>```blade
>@test([ Test1::class, Test2::class, Test3::class ])
>```

**Comment by haidubogdan** [comment]
I think the issue was more or less present in the new version.
Currently the lexer has a workaround to avoid sending the embedding text to php if it contains syntax like `(:` `identifier:identifier` which seem to trigger the Php Emebedding freeze.

By splitting the text to be sent for embedding the corner case with `(:` should be avoided. But it could have the side effect of strange php highlight coloring. So it needs to be monitored.

**Comment by parallels999** [comment]
Thanks, seems to be working again
