### ISSUE TITLE
[BUG] Netbeans freezes on `?:` ternary operator.

### ISSUE THREAD

**Issue by parallels999** [haidubogdan/netbeans-php-blade-plugin#65]
Try to write letter by letter on a blade file
```blade
@test($test ?: $default)
```

**Comment by haidubogdan** [comment]
Hi,
Thank you for the observation.
Should be ok with the latest release : https://github.com/haidubogdan/netbeans-php-blade-plugin/releases

**Comment by parallels999** [comment]
Thanks

**Comment by haidubogdan** [comment]
It seems that the presence of '?' near ':' charcter still triggers freeze on delete action.

**Comment by haidubogdan** [comment]
After debugging the issue inside the IDE modules. I found to be due to a infinite while loop triggered by Brace Matcher if the first token is a parenthesis or a bracket for which I created a issue https://github.com/apache/netbeans/issues/7803

For the moment the best solution is to not embed parenthesis or combination of parenthesis and brakets for **php** embedded tokens. This implementation is available since version **2.5.05**.  For the moment It covers a maximum of 2 consecutive parenthesis.
